apiVersion: v2
name: recipe-receiver
description: A Helm chart to deploy the recipe receiver app.
type: application
version: 0.3.0
appVersion: "0.1.0"
dependencies:
  - name: function
    version: 2.5.3
    repository: 'oci://hmctsprod.azurecr.io/helm/v1/repo'
